# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0013_auto_20160423_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmenuitem',
            name='allow_subnav',
            field=models.BooleanField(default=False, help_text='NOTE: The sub-menu might might not be displayed, even if checked. It depends on how the menu is being used within your project.', verbose_name='allow sub-menu for this item'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='allow_subnav',
            field=models.BooleanField(default=True, help_text='NOTE: The sub-menu might might not be displayed, even if checked. It depends on how the menu is being used within your project.', verbose_name='allow sub-menu for this item'),
        ),
    ]
