# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-30 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0015_auto_20160423_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatmenuitem',
            name='handle',
            field=models.CharField(blank=True, help_text='Used to identify a specific menu item in the template code.', max_length=100),
        ),
        migrations.AddField(
            model_name='mainmenuitem',
            name='handle',
            field=models.CharField(blank=True, help_text='Used to identify a specific menu item in the template code.', max_length=100),
        ),
    ]
