# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0015_auto_20160423_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatmenuitem',
            name='link_handle',
            field=models.SlugField(blank=True, help_text='Used to reference this menu item in templates etc. Must be unique for the selected site.', max_length=100),
        ),
        migrations.AddField(
            model_name='mainmenuitem',
            name='link_handle',
            field=models.SlugField(blank=True, help_text='Used to reference this menu item in templates etc. Must be unique for the selected site.', max_length=100),
        ),
    ]
