# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0016_auto_20160930_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmenu',
            name='handle',
            field=models.SlugField(help_text='Used to reference this menu in templates etc. Must be unique for the selected site.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='flatmenu',
            name='heading',
            field=models.CharField(blank=True, help_text='If supplied, appears above the menu when rendered.', max_length=255, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='flatmenu',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_menus', to='wagtailcore.Site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='flatmenu',
            name='title',
            field=models.CharField(help_text='For internal reference only.', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='flatmenuitem',
            name='handle',
            field=models.CharField(blank=True, help_text='Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='flatmenuitem',
            name='link_text',
            field=models.CharField(blank=True, help_text='Must be set if you wish to link to a custom URL.', max_length=255, verbose_name='link text'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='handle',
            field=models.CharField(blank=True, help_text='Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='link_text',
            field=models.CharField(blank=True, help_text='Must be set if you wish to link to a custom URL.', max_length=255, verbose_name='link text'),
        ),
    ]
