# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models
from django.util.translations import ugettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0016_auto_20160930_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmenu',
            name=_('handle'),
            field=models.SlugField(help_text=_('Used to reference this menu in templates etc. '
                                               'Must be unique for the selected site.'),
                                   max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='flatmenu',
            name='heading',
            field=models.CharField(blank=True,
                                   help_text=_('If supplied, appears above the menu when rendered.'),
                                   max_length=255,
                                   verbose_name=_('heading')),
        ),
        migrations.AlterField(
            model_name='flatmenu',
            name='title',
            field=models.CharField(help_text=_('For internal reference only.'), max_length=255, verbose_name=_('title')),
        ),
        migrations.AlterField(
            model_name='flatmenuitem',
            name='handle',
            field=models.CharField(blank=True,
                                   help_text=_('Use this field to optionally specify an additional value for each menu '
                                               'item, which you can then reference in custom menu templates.'),
                                   max_length=100,
                                   verbose_name=_('handle')),
        ),
        migrations.AlterField(
            model_name='flatmenuitem',
            name='link_text',
            field=models.CharField(blank=True,
                                   help_text=_('Must be set if you wish to link to a custom URL.'),
                                   max_length=255,
                                   verbose_name=_('link text')),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name=_('handle'),
            field=models.CharField(blank=True,
                                   help_text=_('Use this field to optionally specify an additional value for each '
                                             'menu item, which you can then reference in custom menu templates.'),
                                   max_length=100,
                                   verbose_name=_('handle')),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='link_text',
            field=models.CharField(blank=True,
                                   help_text=_('Must be set if you wish to link to a custom URL.'),
                                   max_length=255,
                                   verbose_name=_('link text')),
        ),
    ]
