# Generated by Django 2.1.3 on 2018-11-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0022_auto_20170913_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmenu',
            name='handle',
            field=models.SlugField(allow_unicode=True, help_text='Used to reference this menu in templates etc. Must be unique for the selected site.', max_length=100, verbose_name='handle'),
        ),
    ]
