# Generated by Django 2.1.2 on 2018-11-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0022_auto_20170913_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmenu',
            name='handle',
            field=models.SlugField(allow_unicode=True, help_text='Used to reference this menu in templates etc. Must be unique for the selected site.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='flatmenuitem',
            name='handle',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='handle',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.', max_length=100, verbose_name='handle'),
        ),
    ]
