# Generated by Django 2.1.9 on 2019-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0022_auto_20170913_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatmenu',
            name='use_specific',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='use_specific',
        ),
    ]
