# Generated by Django 2.1.3 on 2018-11-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_auto_20181103_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmenuitem',
            name='handle',
            field=models.SlugField(allow_unicode=True, help_text='Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='handle',
            field=models.SlugField(allow_unicode=True, help_text='Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.', max_length=100, verbose_name='handle'),
        ),
    ]
